title: stefano zingaro
email: stefano.zingaro@unibo.it
description: >- # this means to ignore newlines until "baseurl:"
  academic web page for sharing resources
baseurl: "/~zingaro" 
url: "https://cs.unibo.it" 

# Build settings
theme: minima

minima:
  skin: auto

header_pages:
  - contact.markdown
  - teaching.markdown
  - publications.markdown
  # - talks.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
  - README.md
  - LICENSE
